Improve build script
- Use precompiled headers
- Build Nuklear into static lib

diff --git a/build-plz b/build-plz
--- a/build-plz
+++ b/build-plz
@@ -6,10 +6,12 @@ colored() {
               blue='0;34'  purple='0;35'  cyan='0;36'   lgray='0;37' \
               dgray='1;30' lred='1;31'    lgreen='1;32' yellow='1;33' \
               lblue='1;34' lpurple='1;35' lcyan='1;36'  white='1;37'
-        echo -e "\e[${!1}m$2\e[0m"
+        echo -en "\e[${!1}m$2\e[0m"
     else
-        echo "$2"
+        echo -n "$2"
     fi
+
+    [ -z "$3" ] && echo
 }
 
 fail() {
@@ -36,12 +38,225 @@ progress() {
     printf '\n'
 }
 
+mstime() {
+    echo $(($(date +%s%N)/1000000))
+}
+
+measure() {
+    local start_tm=$1
+    echo "scale=2; $(($(mstime) - start_tm))/1000" | bc -l
+}
+
+declare -A INCLUDE_MAP
+
+_include_scan() {
+    local fname="$1"
+    local cur_dir="$2"
+    for f in $(cat "$fname" 2>/dev/null | grep -E "^[ \t]*#include[ \t]+\"" 2>/dev/null); do
+        [ $f = '#include' ] && continue
+
+        f="${f#*\"}"
+        f="${f%*\"}"
+
+        local current_fname="$cur_dir/$f"
+        current_fname="${current_fname#./}"
+        current_fname="${current_fname#/}"
+
+        [ -z "${INCLUDE_MAP[$current_fname]}" ] && \
+            INCLUDE_MAP["$current_fname"]=true || \
+            continue
+
+        echo "$current_fname"
+
+        local current_dir="$(dirname "$current_fname")"
+        current_dir="${current_dir#./}"
+
+        _include_scan "$current_fname" "$current_dir"
+    done | sort | uniq
+}
+
+include_scan() {
+    echo "$1"
+    _include_scan "$1" "$(dirname "$1")"
+    declare -A INCLUDE_MAP
+}
+
+build_static_lib() {
+    local name="$1"
+    local build_source="$2"
+    local builddir="$3"
+    local CXX_COMPILER="$4"
+    local debug="$5"
+    local flags="$6"
+    local libs="$7"
+
+    local list="$builddir/.ezbld/$name-list" newlist="$builddir/.ezbld/new-$name-list"
+
+    rm -f "$newlist"
+    for f in $(include_scan "$build_source"); do
+        stat --printf="%Y:%n\n" "$f" >> "$newlist"
+    done
+
+    if [ ! -f "$list" ] || \
+        ! cmp --silent "$list" "$newlist"; then
+        rm -f "$builddir/$name-list"
+
+        local start_tm=$(mstime)
+        colored yellow "Building lib$name.a ... " n
+
+        local cmd="$(command -v "$CXX_COMPILER") -c -std=c++20 \
+            $([ "$debug" == true ] && echo "-O0 -g" || echo "-O2 -march=native") \
+            $flags \
+            -L '$(pwd)/$builddir/3rd/lib' \
+            -L '$(pwd)/$builddir/3rd/lib64' \
+            -L '$(pwd)/$builddir' \
+            -isystem '$(pwd)/$builddir/3rd/include' '$(pwd)/$build_source' \
+            -o '$(pwd)/$builddir/$name.o' \
+            $libs"
+        cmd="$(echo "$cmd" | sed 's/  */ /g' | tr '\n' ' ')"
+
+        eval $cmd || fail "Build failed"
+
+        ar rcs "$(pwd)/$builddir/lib$name.a" "$(pwd)/$builddir/$name.o" || fail "Build failed"
+        rm -f "$builddir/$name.o"
+
+        mv -f "$newlist" "$list"
+        printf '%s\n%s\n' "source=\"$(pwd)/$build_source\"" "command=\"$cmd\"" > "$builddir/.ezbld/$name-command"
+
+        colored lgreen "done! $(measure $start_tm)s"
+    else
+        colored lpurple "lib$name.a already built"
+        rm -f "$newlist"
+    fi
+}
+
+build_executable() {
+    local name="$1"
+    local build_source="$2"
+    local builddir="$3"
+    local CXX_COMPILER="$4"
+    local debug="$5"
+    local flags="$6"
+    local libs="$7"
+
+    local list="$builddir/.ezbld/$name-list" newlist="$builddir/.ezbld/new-$name-list"
+
+    rm -f "$newlist"
+    for f in $(include_scan "$build_source"); do
+        stat --printf="%Y:%n\n" "$f" >> "$newlist"
+    done
+
+    if [ ! -f "$list" ] || \
+        ! cmp --silent "$list" "$newlist"; then
+        rm -f "$list"
+
+        local start_tm=$(mstime)
+        colored yellow "Building $name ... " n
+        local cmd="$(command -v "$CXX_COMPILER") -std=c++20 \
+            $([ "$debug" == true ] && echo "-O0 -g" || echo "-O2 -march=native") \
+            $flags \
+            -L '$(pwd)/$builddir/3rd/lib' \
+            -L '$(pwd)/$builddir/3rd/lib64' \
+            -L '$(pwd)/$builddir' \
+            -isystem '$(pwd)/$builddir/3rd/include' '$(pwd)/$build_source' \
+            -o '$(pwd)/$builddir/$name' \
+            $libs"
+        cmd="$(echo "$cmd" | sed 's/  */ /g' | tr '\n' ' ')"
+
+        eval $cmd || fail "Build failed"
+        mv -f "$newlist" "$list"
+        printf '%s\n%s\n' "source=\"$(pwd)/$build_source\"" "command=\"$cmd\"" > "$builddir/.ezbld/$name-command"
+
+        colored lgreen "done! $(measure $start_tm)s"
+    else
+        colored lpurple "$name already built"
+        rm -f "$newlist"
+    fi
+}
+
+make_pch() {
+    local location="$1"
+    local builddir="$2"
+    local CXX_COMPILER="$3"
+    local debug="$4"
+    local flags="$5"
+    local name='PCH'
+
+    [ -f "$location" ] || return 0
+
+    local list="$builddir/.ezbld/$name-list" newlist="$builddir/.ezbld/new-$name-list"
+
+    rm -f "$newlist"
+    for f in $(include_scan "$location"); do
+        stat --printf="%Y:%n\n" "$f" >> "$newlist"
+    done
+
+    if [ ! -f "$list" ] || \
+        ! cmp --silent "$list" "$newlist" || \
+        [ "$(cat "$location.gch.builddir" 2>/dev/null)" != "$builddir" ] || \
+        [ ! -f "$location.gch" ]; then
+        rm -f "$list"
+
+        local start_tm=$(mstime)
+        colored yellow "Making precompiled header $location ... " n
+        local cmd="$(command -v "$CXX_COMPILER") -std=c++20 -c \
+            $([ "$debug" == true ] && echo "-O0 -g" || echo "-O2 -march=native") \
+            $flags \
+            -L '$(pwd)/$builddir/3rd/lib' \
+            -L '$(pwd)/$builddir/3rd/lib64' \
+            -L '$(pwd)/$builddir' \
+            -isystem '$(pwd)/$builddir/3rd/include' '$(pwd)/$location' \
+            -o $location.gch"
+        cmd="$(echo "$cmd" | sed 's/  */ /g' | tr '\n' ' ')"
+
+        eval $cmd || fail " Failed"
+
+        mv -f "$newlist" "$list"
+        echo "$builddir" > "$location.gch.builddir"
+
+        MAKED_PCH="$location"
+
+        colored lgreen "done! $(measure $start_tm)s"
+    else
+        colored lpurple "$name already built"
+        rm -f "$newlist"
+    fi
+}
+
+gen_compodb() {
+    local builddir="$1"
+
+    echo "[" > ./compile_commands.json
+
+    local targets="$(ls $builddir/.ezbld/*-command)"
+    local count=$(echo "$targets" | wc -w);
+    local idx=0
+
+    for f in $targets; do
+        idx=$((idx+1))
+        local end_seq="},"
+        [ $idx = $count ] && end_seq="}"
+
+        . "$f"
+
+        cat >> ./compile_commands.json <<EOF
+{
+  "directory": "$(pwd)/$builddir",
+  "command": "$command",
+  "file": "$source"
+$end_seq
+EOF
+    done
+    echo "]" >> ./compile_commands.json
+}
+
 _build() {
     local CXX_COMPILER="${CXX_COMPILER:=/usr/bin/g++-10}"
     local C_COMPILER="${C_COMPILER:=/usr/bin/gcc-10}"
     local builddir='./easybuild'
     local rebuild_submodules=false
     local compodb=false
+    local debug=false
     local run_args=
 
     local hardening_flags="
@@ -69,6 +284,7 @@ _build() {
         case "$1" in
         --builddir=*)
             builddir="${1#*=}"
+            [ "$debug" = true ] && builddir="$builddir-debug"
             ;;
         --rebuild-subs)
             rebuild_submodules=true
@@ -76,9 +292,18 @@ _build() {
         --compodb)
             compodb=true
             ;;
+        --debug)
+            debug=true
+            builddir="$builddir-debug"
+            ;;
         --run)
             shift
             run_args="LD_LIBRARY_PATH='$builddir/3rd/lib:$builddir/3rd/lib64' $builddir/$@"
+            break
+            ;;
+        --gdbrun)
+            shift
+            run_args="LD_LIBRARY_PATH='$builddir/3rd/lib:$builddir/3rd/lib64' gdb --args $builddir/$@"
             break
             ;;
         *)
@@ -89,6 +314,7 @@ _build() {
     done
 
     mkdir -p "$builddir/3rd"
+    mkdir -p "$builddir/.ezbld"
     mkdir -p "$builddir/submodules/SFML"
 
     if [ ! -f "$builddir/submodules/SFML/.easybuild_done" ] || [ "$rebuild_submodules" == true ]; then
@@ -115,47 +341,41 @@ _build() {
         cp 'submodules/Nuklear/nuklear.h' "$builddir/3rd/include/"
     fi
 
-    rm -f "$builddir/.new-easybuild-list"
-    for f in 'diefastdiehard.cpp' $(ls -w1 src/*); do
-        stat --printf="%Y:%n\n" "$f" >> "$builddir/.new-easybuild-list"
-    done
+    make_pch \
+        src/stdafx.hpp \
+        "$builddir" \
+        "$CXX_COMPILER" \
+        "$debug" \
+        "$hardening_flags"
 
-    if [ ! -f "$builddir/.easybuild-list" ] || \
-        ! cmp --silent "$builddir/.easybuild-list" "$builddir/.new-easybuild-list"; then
-        rm -f "$builddir/.easybuild-list"
+    build_static_lib \
+        nuklear \
+        src/nuklear.cpp \
+        "$builddir" \
+        "$CXX_COMPILER" \
+        "$debug" \
+        "$hardening_flags" \
+        "-lsfml-system -lsfml-window -lsfml-graphics -lGL -lGLEW"
 
-        colored yellow "Building $builddir/dfdh"
-        local cmd="$(command -v "$CXX_COMPILER") -std=c++20 \
-            -O2 -march=native \
-            $hardening_flags \
-            -L '$(pwd)/$builddir/3rd/lib' \
-            -L '$(pwd)/$builddir/3rd/lib64' \
-            -isystem '$(pwd)/$builddir/3rd/include' '$(pwd)/diefastdiehard.cpp' \
-            -o '$(pwd)/$builddir/dfdh' \
-            -lsfml-system -lsfml-window -lsfml-graphics -lsfml-network -lpthread -lGL -lGLEW"
-        cmd="$(echo "$cmd" | sed 's/  */ /g' | tr '\n' ' ')"
+    build_executable \
+        dfdh \
+        diefastdiehard.cpp \
+        "$builddir" \
+        "$CXX_COMPILER" \
+        "$debug" \
+        "$hardening_flags" \
+        "-lnuklear -lsfml-system -lsfml-window -lsfml-graphics -lsfml-network -lpthread -lGL -lGLEW"
 
-        eval $cmd || fail "Build failed"
+    build_executable \
+        gui-test \
+        gui_test.cpp \
+        "$builddir" \
+        "$CXX_COMPILER" \
+        "$debug" \
+        "$hardening_flags" \
+        "-lnuklear -lsfml-system -lsfml-window -lsfml-graphics -lGL -lGLEW"
 
-        if [ "$compodb" = true ]; then
-            cat > ./compile_commands.json <<EOF
-[
-{
-  "directory": "$(pwd)/$builddir",
-  "command": "$cmd",
-  "file": "$(pwd)/diefastdiehard.cpp"
-}
-]
-EOF
-        fi
-
-        mv -f "$builddir/.new-easybuild-list" "$builddir/.easybuild-list"
-
-        colored lgreen "Build done"
-    else
-        colored yellow "Already built in $builddir/dfdh"
-        rm -f "$builddir/.new-easybuild-list"
-    fi
+    [ "$compodb" = true ] && gen_compodb "$builddir"
 
     eval $run_args
 }
